# Generated by Django 3.1.6 on 2021-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210209_0425'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choice',
            name='unique_choice_text_constraint',
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'choice_text'), name='unique_choice_text_per_question_constraint'),
        ),
    ]
